name: Continuous Integration for Machine Learning Applications
on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - feature/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6

      - name: Generate dynamic matrix from templates.xml
        id: set-matrix
        run: |
          matrix=$(python3 .github/workflows/scripts/generate_matrix.py | jq -c .)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    env:
      SISDK_VERSION: 2025.12.2
      AIML_VERSION: 2.2.1
    steps:
      - name: Install SLT
        shell: bash
        env:
          SLT_DOWNLOAD_URL: https://www.silabs.com/documents/public/software/slt-cli-1.1.4-linux-x64.zip
          SLT_PKG_NAME: slt-linux-x64.zip
        run: |
          curl ${SLT_DOWNLOAD_URL} --output ${RUNNER_TEMP}/${SLT_PKG_NAME}
          # check if we got the binary or a webpage, fail on webpage.
          jq -e . ${RUNNER_TEMP}/${SLT_PKG_NAME} >/dev/null 2>&1 && cat ${RUNNER_TEMP}/${SLT_PKG_NAME}
          mkdir -p $HOME/.local/bin
          unzip -o ${RUNNER_TEMP}/${SLT_PKG_NAME} -d $HOME/.local/bin
          chmod +x $HOME/.local/bin/slt
          rm ${RUNNER_TEMP}/${SLT_PKG_NAME}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "SLT_CI=true" >> $GITHUB_ENV

      - name: Install Conan
        shell: bash
        run: |
          slt install conan

          # Define paths as variables
          echo "CONAN_HOME=$HOME/.silabs/slt/installs/conan" >> $GITHUB_ENV
          echo "$HOME/.silabs/slt/engines/conan/conan" >> $GITHUB_PATH

      - name: Check Conan Install
        shell: bash
        run: |
          echo "conan-version=$(conan --version | head -n 1)" >> $GITHUB_OUTPUT
          echo "conan-path=$(which conan)" >> $GITHUB_OUTPUT

          cat "$GITHUB_OUTPUT" || true

      - name: Install Build Tools
        shell: bash
        run: |
          slt install cmake ninja gcc-arm-none-eabi/12.2.rel1 -e conan

      - name: Setup Build Tool paths
        shell: bash
        run: |
          echo "$(slt where ninja)" >> "$GITHUB_PATH"
          echo "$(slt where cmake)/bin" >> "$GITHUB_PATH"

          ARM_GCC_DIR="$(slt where gcc-arm-none-eabi)"
          echo "ARM_GCC_DIR=$ARM_GCC_DIR" >> "$GITHUB_ENV"
          echo "$ARM_GCC_DIR/bin" >> "$GITHUB_PATH"

      - name: Install SLC CLI
        shell: bash
        run: |
          slt install slc-cli

      - name: Setup SLC CLI paths
        shell: bash
        run: |
          SLC_CLI_PATH="$(slt where slc-cli)"
          echo "UC_CLI_DIR=$SLC_CLI_PATH" >> $GITHUB_ENV
          echo "$SLC_CLI_PATH" >> $GITHUB_PATH

      - name: Install SDKs
        shell: bash
        run: slt install "simplicity-sdk/$SISDK_VERSION" "aiml/$AIML_VERSION" -e conan

      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Generate + Build
        env:
          APP: ${{ matrix.app }}
          BOARD: ${{ matrix.board }}
        run: |
          set -e
          echo "App: $APP"
          echo "BOARD: $BOARD"
          slc generate \
            -d target/$APP/$BOARD \
            -p $APP.slcp \
            --with $BOARD \
            --sdk-package-path "$(slt where simplicity-sdk/$SISDK_VERSION)" \
            --sdk-package-path "$(slt where aiml/$AIML_VERSION)" \
            --sdk-package-path .

          cd target/$APP/$BOARD/cmake_gcc
          cmake --workflow --preset project
          echo "==> Listing generated .s37 files" 
          find ./target -name "*.s37"
