name: Ubuntu env -> SLC setup (uses SSH & Artifactory secrets) latestrere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-to-slc:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Start
        shell: bash
        run: |
          echo "==> Workflow: Ubuntu env -> SLC setup (through step 16)"
          echo "==> Repo: $GITHUB_REPOSITORY | Ref: $GITHUB_REF | SHA: $GITHUB_SHA"

      - name: 📥 Checkout (public)
        uses: actions/checkout@v5
        with:
          submodules: recursive

      # ------- SSH KEY SETUP (no expressions inside the script) -------
      - name: 🔑 SSH key setup (for internal git over SSH)
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}   # may be empty
        run: |
          set -e
          if [ -n "$SSH_PRIVATE_KEY" ]; then
            echo "==> SSH key provided: configuring ~/.ssh"
            mkdir -p ~/.ssh
            printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            touch ~/.ssh/known_hosts
            echo "==> Preloading known_hosts for stash-mirror.silabs.com & github.com"
            ssh-keyscan -T 5 stash-mirror.silabs.com 2>/dev/null >> ~/.ssh/known_hosts || true
            ssh-keyscan -T 5 github.com 2>/dev/null >> ~/.ssh/known_hosts || true
            echo "==> SSH ready."
          else
            echo "!! No SSH_PRIVATE_KEY secret found. Internal SSH clones will be skipped."
          fi

      - name: 🖥️ System info
        shell: bash
        run: |
          echo "==> uname -a"; uname -a
          echo "==> /etc/os-release"; cat /etc/os-release
          echo "==> whoami: $(whoami) | home: $HOME | workdir: $(pwd)"
          echo "==> Disk usage:"; df -h .

      - name: 📂 Create ~/src ~/venvs ~/tools
        shell: bash
        run: |
          set -e
          echo "==> Creating developer directories..."
          mkdir -p "$HOME/src" "$HOME/venvs" "$HOME/tools"
          ls -la "$HOME" | sed -n '1,120p'

      - name: 📦 Apt update & essentials
        shell: bash
        run: |
          set -e
          echo "==> apt update"; sudo apt update -y
          echo "==> install essentials"
          sudo apt install -y git curl wget unzip build-essential cmake make \
                               python3 python3-pip python3-venv pkg-config \
                               libssl-dev libffi-dev python3-dev ninja-build \
                               telnet netcat-openbsd
          echo "==> Versions:"
          python3 --version || true
          pip3 --version || true
          cmake --version || true
          ninja --version || true

      - name: ☕ Install OpenJDK 17 + set JAVA_HOME
        shell: bash
        run: |
          set -e
          echo "==> Installing OpenJDK 17"; sudo apt install -y openjdk-17-jdk
          echo "==> java -version"; java -version
          echo "==> Setting JAVA_HOME"
          echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> "$HOME/.bashrc"
          source "$HOME/.bashrc" || true
          echo "JAVA_HOME=$JAVA_HOME"

      - name: 🛠️ ARM GCC toolchain (12.2.rel1)
        shell: bash
        run: |
          set -e
          cd "$HOME/tools"
          echo "==> Download ARM toolchain 12.2.rel1"
          wget -q https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
          echo "==> Extract"
          tar xf arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
          rm arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
          echo "==> GCC version"
          "$HOME/tools/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc" --version | head -n 1

      - name: 🧱 CMake & 🪄 Ninja versions
        shell: bash
        run: |
          echo "==> CMake version"; cmake --version || true
          echo "==> Ninja version"; ninja --version || true

      - name: 📦 Git LFS install & init
        shell: bash
        run: |
          set -e
          echo "==> Install Git LFS"
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt install -y git-lfs
          echo "==> git lfs install"
          git lfs install

      - name: 📚 Clone GSDK (public)
        shell: bash
        run: |
          set -e
          cd "$HOME/src"
          echo "==> Cloning public GSDK"
          git clone https://github.com/SiliconLabs/simplicity_sdk.git gsdk
          cd "$HOME/src/gsdk"
          echo "==> Init core submodules"
          git submodule update --init --recursive util/third_party/cmsis
          git submodule update --init --recursive util/third_party/unity
          git submodule update --init --recursive util/third_party/printf
          echo "==> LFS pull (best effort)"
          git lfs pull || true

      - name: 🌱 Create Python venv (sisdk)
        shell: bash
        run: |
          set -e
          python3 -m venv "$HOME/venvs/sisdk"
          source "$HOME/venvs/sisdk/bin/activate"
          python -V; pip -V
          echo "==> Upgrading pip"
          pip install --upgrade pip

      # ---------- SLC (Step 16) ----------
      - name: 🧩 Clone SLC CLI over SSH (internal)
        shell: bash
        env:
          HAVE_SSH: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -e
          if [ -n "$HAVE_SSH" ]; then
            echo "==> Attempting SSH clone of slc_cli from stash-mirror.silabs.com"
            cd "$HOME/tools"
            git clone ssh://git@stash-mirror.silabs.com/simplicity_studio/slc_cli.git || { echo "!! slc_cli clone failed"; exit 1; }
            echo "==> slc_cli cloned."
          else
            echo "!! SSH key not provided; cannot clone slc_cli over SSH. Skipping SLC clone."
            exit 0
          fi

      - name: 📜 Install SLC CLI Python deps (via Artifactory creds if provided)
        shell: bash
        env:
          ARTI_URL: ${{ vars.ARTIFACTORY_PYPI_URL }}         # may be empty
          ARTI_USER: ${{ secrets.ARTIFACTORY_USERNAME }}     # may be empty
          ARTI_KEY:  ${{ secrets.ARTIFACTORY_API_KEY }}      # may be empty
        run: |
          set -e
          if [ ! -d "$HOME/tools/slc_cli" ]; then
            echo "!! slc_cli directory not found (clone likely skipped). Skipping deps install."
            exit 0
          fi

          source "$HOME/venvs/sisdk/bin/activate"

          # bash-side fallback for URL (no expressions)
          if [ -z "$ARTI_URL" ]; then
            ARTI_URL="https://artifactory.silabs.net/artifactory/api/pypi/gsdk-pypi/simple"
          fi
          echo "==> Using Artifactory URL: $ARTI_URL"

          python -m pip install --upgrade setuptools

          if [ -f "$HOME/tools/slc_cli/requirements.txt" ]; then
            if [ -n "$ARTI_USER" ] && [ -n "$ARTI_KEY" ]; then
              echo "==> Artifactory creds present; using authenticated index (credentials masked)"
              hostpath="${ARTI_URL#https://}"
              PIP_INDEX_URL="https://${ARTI_USER}:${ARTI_KEY}@${hostpath}"
              PIP_INDEX_URL="$PIP_INDEX_URL" pip install --index-url "$PIP_INDEX_URL" -r "$HOME/tools/slc_cli/requirements.txt"
            else
              echo "!! No Artifactory creds provided; trying default pip index (may fail if deps are internal)"
              pip install -r "$HOME/tools/slc_cli/requirements.txt" || true
            fi
          else
            echo "requirements.txt not found; skipping SLC deps install."
          fi

          echo "==> SLC deps install step complete."

      - name: 🔧 Export SLC env & PATH
        shell: bash
        run: |
          set -e
          if [ -d "$HOME/tools/slc_cli" ]; then
            echo "==> Exporting env vars for SLC"
            {
              echo 'export UC_CLI_DIR="$HOME/tools/slc_cli"'
              echo 'export SLC_JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"'
              echo 'export PATH="$PATH:$UC_CLI_DIR"'
            } >> "$HOME/.bashrc"
            source "$HOME/.bashrc" || true
            echo "UC_CLI_DIR=$UC_CLI_DIR"
            echo "SLC_JAVA_HOME=$SLC_JAVA_HOME"
            which slc || true
          else
            echo "!! slc_cli not present; skipping env PATH export."
          fi

      - name: 🚀 Initialize SLC & configure SDK
        shell: bash
        run: |
          set -e
          if [ -d "$HOME/tools/slc_cli" ]; then
            source "$HOME/venvs/sisdk/bin/activate"
            echo "==> slc -h"; slc -h || true
            echo "==> slc configuration --sdk"; slc configuration --sdk "$HOME/src/gsdk" || true
            echo "==> slc signature trust --sdk"; slc signature trust --sdk "$HOME/src/gsdk" || true
            if [ -d "$HOME/src/gsdk/extension/aiml-extension" ]; then
              echo "==> slc signature trust --extension-path (aiml-extension)"
              slc signature trust --extension-path "$HOME/src/gsdk/extension/aiml-extension" || true
            else
              echo "==> aiml-extension not present; skipping extension trust."
            fi
          else
            echo "!! slc_cli not present; skipping SLC init/config."
          fi

      - name: 🏁 Done (stop after SLC setup)
        shell: bash
        run: |
          echo "==> Finished through step 16 (SLC setup)."
          echo "==> If SLC clone failed, confirm SSH_PRIVATE_KEY is added as a secret."
          echo "==> If deps failed, confirm ARTIFACTORY_USERNAME/API_KEY and (optionally) ARTIFACTORY_PYPI_URL."
